apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dremio-dataset-query.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dremio-dataset-query.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dremio-dataset-query.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: python-script-volume
              mountPath: /usr/src/app
          command: ["python3"]
          args: ["/usr/src/app/dataset-deploy-request.py"]
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DREMIO_SANDBOX_PROJECT_ID
              value: {{ .Values.sandboxProjectId }}
            - name: DREMIO_PROD_PROJECT_ID
              value: {{ .Values.prodProjectId }}
            - name: DREMIO_SANDBOX_KEY
                valueFrom:
                    secretKeyRef:
                        name: dremio-sandbox-secret
                        key: sandbox_key
            - name: DREMIO_PROD_KEY
                valueFrom:
                    secretKeyRef:
                        name: dremio-prod-secret
                        key: prod_key
      volumes:
        - name: python-script-volume
          configMap:
            name: {{ include "dremio-dataset-query.fullname" . }}
            items:
              - key: dataset-deploy-request.py
                path: dataset-deploy-request.py